#include "auxiliar/pausar.h"
#include "auxiliar/limparTela.h"
#include "auxiliar/menu.h"
#include "auxiliar/mostrarPassos.h"

#include "op_vectors/troca.h"
#include "op_vectors/plotGraph.h"
#include "op_vectors/printVector.h"
#include "op_vectors/randomVector.h"
#include "op_vectors/configurations.h"

#include "sort/insertionSort.h"
#include "sort/selectionSort.h"
#include "sort/bubbleSort.h"
#include "sort/comparaTempo.h"
